src/LivrariaNerd.Web.UI/Controllers/ProdutoController.cs
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using LivrariaNerd.Domain.Entities;
using LivrariaNerd.Infra.Data.Interface;
using Microsoft.AspNetCore.Hosting;
using System.IO;
using Microsoft.AspNetCore.Http;
using System.Security.Cryptography;
using System;
using System.Text;

namespace e_commerce_ws.Controllers
{
    [Route("produto")]
    public class ProdutoController : Controller
    {
        private readonly IBaseRepositoryAsync<Produto> _repo;
        private readonly IProdutoRepository _produtoRepository;
        private readonly IHostingEnvironment _env;
        private readonly string _nomePasta;
        private readonly string _caminho;

        public ProdutoController(IBaseRepositoryAsync<Produto> context, IProdutoRepository produtoRepository, IHostingEnvironment env, IHttpContextAccessor httpContextAccessor)
        {
            _repo = context;
            _produtoRepository = produtoRepository;
            _env = env;

            string wwwroot = env.WebRootPath;

            _nomePasta = "uploads";
            _nomePasta = Path.Combine(_nomePasta, "imagens");
            _caminho = Path.Combine(wwwroot, _nomePasta);

            if (!Directory.Exists(_caminho))
            {
                Directory.CreateDirectory(_caminho);
            }

            //Pegar o Id do usuario por claim
            //var claimsIdentity = (ClaimsIdentity)httpContextAccessor.HttpContext.User.Identity;
            //var idUsuario = claimsIdentity.FindFirst("Id").Value;
        }

        [HttpPost, Route("upload")]
        public IActionResult Upload(IFormFile file, int id)
        {
            var nomeArquivo = file.FileName;

            var produto = _repo.ObterPeloId(id);

            //Hash
            FileInfo fileInfo = new FileInfo(nomeArquivo);
            var crypt = new SHA256Managed();
            var hash = new StringBuilder();
            byte[] crypto = crypt.ComputeHash(Encoding.UTF8.GetBytes(fileInfo.Name.Replace(fileInfo.Extension, "") + DateTime.Now));
            foreach (byte oByte in crypto)
            {
                hash.Append(oByte.ToString("x2"));
            }

            var caminhoArquivo = Path.Combine(_caminho, (hash + fileInfo.Extension).ToUpper());

            var caminhoWWWRoot = Path.Combine(_nomePasta, (hash + fileInfo.Extension).ToUpper());

            using (var stream = new FileStream(caminhoArquivo, FileMode.Create))
            {
                file.CopyTo(stream);
                //Add The Image to the product object
                produto.ImagemCaminhoCompleto = caminhoArquivo;
                produto.ImagemCaminhoWwwroot = "/" + caminhoWWWRoot;
                _repo.Alterar(produto);
            }

            return RedirectToAction("Index");
        }

        [HttpGet, Route("obtertodos")]
        public JsonResult ObterTodos(string busca)
        {
            if (busca == null)
                busca = "";
                
            var produtos = _produtoRepository.ObterTodosBusca(busca);
            return Json(produtos);
        }

        [HttpGet, Route("obtertodospelacategoria")]
        public JsonResult ObterTodos(int id)
        {
            var cidades = _produtoRepository.ObterTodosPelaCategoria(id);
            return Json(cidades);
        }

        [HttpGet, Route("obterpeloid")]
        public ActionResult ObterPeloId(int id)
        {
            var produto = _produtoRepository.ObterPeloId(id);

            if (produto == null)
            {
                return NotFound();
            }

            return Json(produto);
        }

        [HttpPost, Route("adicionar")]
        public async Task<JsonResult> Adicionar(Produto produto)
        {
            string precoString = Request.Form["preco"];
            if (precoString.Contains(","))
            {
                precoString = precoString.Replace(",", ".");
            }
            else if (precoString.Contains("."))
            {
                precoString = precoString.Replace(".", ",");
            }

            produto.Preco = Convert.ToDecimal(precoString);

            int id = await _repo.Adicionar(produto);
            return Json(new { id = id });

        }

        [HttpPost, Route("alterar")]
        public JsonResult Alterar(Produto produto)
        {

            string precoString = Request.Form["preco"];
            if (precoString.Contains(","))
            {
                precoString = precoString.Replace(",", ".");
            }
            else if (precoString.Contains("."))
            {
                precoString = precoString.Replace(".", ",");
            }

            produto.Preco = Convert.ToDecimal(precoString);
            bool alterou = _repo.Alterar(produto);
            return Json(new { status = alterou });
        }

        [HttpGet, Route("apagar")]
        public JsonResult Apagar(int id)
        {
            bool apagou = _repo.Apagar(id);
            return Json(new { status = apagou });
        }

        [HttpGet, Route("")]
        public ActionResult Index()
        {
            return View();
        }



    }
}

src/LivrariaNerd.Web.UI/Controllers/UsuarioProdutoController.cs
using Microsoft.AspNetCore.Mvc;
using LivrariaNerd.Domain.Entities;
using LivrariaNerd.Infra.Data.Interface;
using System.Collections.Generic;

namespace PadawanStore.Web.UI.Controllers
{
    [Route("loja")]
    public class UsuarioProdutoController : Controller
    {
        private readonly IProdutoRepository _produtoRepository;
        private readonly IBaseRepositoryAsync<Produto> _repository;

        public UsuarioProdutoController(IBaseRepositoryAsync<Produto> repository, IProdutoRepository produtoRepository)
        {
            _produtoRepository = produtoRepository;
            _repository = repository;
        }

        [HttpGet, Route("")]
        public IActionResult Index()
        {
            return View();
        }

        [HttpGet, Route("obtertodos")]
        public JsonResult ObterTodos()
        {
            string busca = "";
            var produtos = _produtoRepository.ObterTodos(busca);
            return Json(produtos);
        }

        [HttpGet, Route("obtertodosprodutosusuarios")]
        public JsonResult ObterTodosProdutosUsuarios()
        {
            string busca = "";
            var produtos = _produtoRepository.ObterTodos(busca);

            var result = new List<object>();

            foreach (var produto in produtos)
            {
                result.Add(
                    new
                    {
                        Codigo = produto.Id,
                        ValorDoProduto = produto.Preco,
                        NomeProduto = produto.Nome,
                        NomeCategoriaProduto = produto.Categoria.Nome,
                        ImagemDoProduto = produto.ImagemCaminhoCompleto
                    });
            }

            return Json(result);
        }

        [HttpGet, Route("produtos")]
        public IActionResult Produtos()
        {
            return View();
        }

        [HttpGet, Route("obtertodosbusca")]
        public IActionResult ObterTodosBusca(string busca)
        {
            if (busca == null)
                busca = "";
            var produtos = _produtoRepository.ObterTodosBusca(busca);
            return Json(produtos);
        }

        [HttpGet, Route("obtertodosbuscaecategoria")]
        public IActionResult ObterTodosBuscaECategoria(string busca, int id)
        {
            if (busca == null)
                busca = "";
            var produtos = _produtoRepository.ObterTodosBuscaECategoria(busca, id);
            return Json(produtos);
        }

        [HttpGet, Route("produto")]
        public IActionResult Produto(int id)
        {
            var produto = _produtoRepository.ObterPeloId(id);
            ViewData["Produto"] = produto;

            return View();
        }

    }
}

src/LivrariaNerd.Web.UI/Views/Produto/Produto.cshtml
@{
    ViewData["Title"] = "Produto";
    Layout = "~/Views/Shared/_LayoutUsuario.cshtml";
}


@section Styles{
    <link href="~/css/customizada/loja.css" rel="stylesheet" />
    <link href="~/tema/global/fonts/glyphicons/glyphicons.min.css" rel="stylesheet" />

}


<div class="page-header">
    <h1 class="page-title" id="titulo-produto">[Produto]</h1>
    <ol class="breadcrumb">
        <li class="breadcrumb-item"><a href="@Url.Action("Index","UsuarioProduto")">Loja</a></li>
        <li class="breadcrumb-item active">Produtos</li>
        <li class="breadcrumb-item active" id="bc-titulo-produto">[Produto]</li>
    </ol>
</div>


<div class="page-content">
    <!-- Painel -->
    <div class="panel">

        <!-- Box da Esquerda (Informações do produto)-->
        <div class="row row-lg">
            <div class="col-xl-5 offset-xl-2">
                <img class="img-produto" src="~/img/livro_dnd_manual_monstros.jpg" />
                <h3>Descrição do Produto:</h3>
                <div id="desc-box">
                    <p class="form-control cover-background descricao" style="background-color: rgba(237, 237, 237, 0.59); color: #b4652c" id="descricao">[Descricao do produto]</p>
                </div>
                <div class="vl"></div>
            </div>
            <!-- Box da Direita (Informações de compra) -->
            <div class="col-xl-4 ">
                <div class="col-12">
                    <div class="card" style="width: 18em">
                        <div class="card-body">
                            <div class="row row-lg">
                                <h3 class="card-title azul-escuro">Nome do produto</h3>
                                <h4 class="card-subtitle mt-15 laranja">Preço do produto</h4>
                                <h5 class="ml-5">[categoria produto]</h5>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="row row-lg">
                    <div style="position: absolute; bottom:20%; right: 40%">
                        <button class="btn btn-warning align-baseline btn-floating"><i class="icon glyphicon glyphicon-shopping-cart"></i> </button>
                        <button class="btn btn-danger align-baseline btn-floating"><i class="icon glyphicon glyphicon-heart-empty"></i></button>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<style>
    body {
        overflow-y: scroll;
        overflow-x: hidden;
    }
</style>

@section Scripts {

    <script src="~/js/usuario/pegar-produto.js"></script>
}